services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: rahul
      POSTGRES_PASSWORD: rahul
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
      driver: bridge

volumes:
  postgres:
  pgadmin:


#version: "3.8"
#
#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres:14
#    environment:
#      POSTGRES_USER: rahul
#      POSTGRES_PASSWORD: rahul
#      POSTGRES_DB: mydb
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres-net
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: False
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres-net
#    restart: unless-stopped
#
#networks:
#  postgres-net:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:
#--------------------------------------------------------------------------



